### ISSUE TITLE
Splash screen is shown when a user navigates back

### ISSUE THREAD

**Issue by Felix-Kariuki** [lynnemunini/forecast-app#5]
The splash screen remains in the back stack and is still shown on navigate back

**Comment by lynnemunini** [comment]
Hey Felix! Glad you brought this to my attention. I've deployed a fix for this, please let me know if it works for you. If you notice any other issues, please let me know. Thanks for checking it out!

**Comment by Felix-Kariuki** [comment]
I'll let you know if I notice any more issues. Happy coding🚀

**Comment by lynnemunini** [comment]
Perfect! Happy coding
