### ISSUE TITLE
Extract String Resource

### ISSUE THREAD

**Issue by Gmatieso** [lynnemunini/forecast-app#7]
Would be better if the strings in the apps are extracted to their own file. Wouldn't mind if i contribute to this

**Comment by lynnemunini** [comment]
Thank you @Gmatieso this will be  great improvement! Feel free to go ahead and work on it. Looking forward to seeing your contributions

**Comment by Gmatieso** [comment]
Yap Sure. Working on it...

**Comment by lynnemunini** [comment]
Thanks @Gmatieso PR merged!
